### ISSUE TITLE
Couldnt open map.obtm 

### ISSUE THREAD

**Issue by hadewych** [malucooo/Otxserver-Testing#1]
when I wanna open this error happen

**Comment by DerzeGuilherme** [comment]
What error? What is the size of your map?

**Comment by hadewych** [comment]
I solved it didnt know that u have to download manually the map

**Comment by DerzeGuilherme** [comment]
You can download Git LFS
Git Large File Storage (LFS) replaces large files such as audio samples, videos, datasets, and graphics with text pointers inside Git, while storing the file contents on a remote server like GitHub.com or GitHub Enterprise.
https://git-lfs.github.com/
