### ISSUE TITLE
out of quota for the map

### ISSUE THREAD

**Issue by hadewych** [malucooo/Otxserver-Testing#11]
quota over for map, cant be downloaded

**Comment by Guiaki** [comment]
O pessoal precisa deletar versões passadas do mapa ou comprar mais espaço para que o mapa possa continuar sendo baixado pelo github.
No meio tempo, tem um release do dia 02/novembro aqui:
https://fs13n1.sendspace.com/dl/c71569f40c45016c1fd17323f1a04103/5818f58d7c7dbd62/ochges/global.rar
