### ISSUE TITLE
Skinning bug

### ISSUE THREAD

**Issue by GoularPink** [malucooo/Otxserver-Testing#16]
Use obsidian knife on ice cub, this will create 2 items.

Fix please :D

**Comment by mattyx14** [comment]
¿????

**Comment by GoularPink** [comment]
Use obsidian knife on ice cub, this will create 2 items.

@mattyx14

**Comment by Eternal-Scripts** [comment]
Fix skinning bug 1aaf793543a734b5e0f3598bc44b48981202b204
