### ISSUE TITLE
Store inbox bug

### ISSUE THREAD

**Issue by GoularPink** [malucooo/Otxserver-Testing#17]
If player buy one boots from website and push to slot where have another boots, the old boots go into store inbox.

And if this player take red skull, he push the old boots (leather boots) for dont lost the boots vip ^^
Same with others itens.

Português (sou péssimo em ingles)
Se o player comprar um item no site e por exemplo estiver usando um leather set. Ele comprou uma bota vip e arrastou a bota vip em direção a leather boots, automaticamente a leather boots vai para o store inbox ... Ai se o cara pegar red skull é só ele destrocar a bota vip pela leather inbox para nao dropar...

Para fixar isso teria que impedir que o player arrasta um item comprado para outro lugar a não ser a backpack.

**Comment by degolaot** [comment]
confirmado.

**Comment by Eternal-Scripts** [comment]
Fix store inbox 26e8bba18cb0a266162e2eed6b0ba19e906f57b0
