### ISSUE TITLE
personal map issue

### ISSUE THREAD

**Issue by pitis91** [malucooo/Otxserver-Testing#2]
Hi maybe u know me I'm asking about this repository will be the only one? or will still working the other one?

if the answer is yes I have a rlly huge doubt,
why the map is worst than https://github.com/malucooo/Otxserver-Global/tree/master/data/world ??

thanks and see you :D

**Comment by darkjav** [comment]
@malucooo So in what repository we go to working?

@pitis91 What you mean with "map is worst" , you can specified what problem have the map of Otxserver-Global, in compared with this (Otxserver-Testing)?

**Comment by pitis91** [comment]
is unreal map, and if you open two maps your ask will be answered -.-

**Comment by darkjav** [comment]
You are who needed the answer, i not need... for the next report, please explain more details.

**Comment by pitis91** [comment]
i've don't tryed to be rude, I've just wanted to explain if you open the two maps is visible why i'm talking about for

**Comment by darkjav** [comment]
@pitis91 Hi bro, well, i checked both maps, so i look that the map of Otxserver-Global is lower complete in few areas, there exist some areas incompleted or missing, and this map (Otxserver-Testing) have almost all areas, but the one problem is that rookgaard have houses and one custom area for hunting dragons, wyrms, demons etc...

What another unreal map you can see here?


@malucooo hey bro i need know if we need forget the another repository?
